# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define :master do |master|
    # For Jenkins
    master.vm.network "forwarded_port", guest: 8080, host: 18080

    master.vm.hostname = "ci-master"
    master.vm.network "private_network", ip: "172.28.128.4", :netmask => "255.255.255.0"
  end

  config.vm.define :slave do |slave|
    slave.vm.hostname = "ci-slave"
    slave.vm.network "private_network", ip: "172.28.128.3", :netmask => "255.255.255.0"
  end

end
